# Generated by Django 3.1.7 on 2021-04-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_shipped',
        ),
    ]
